# Generated by Django 2.1.7 on 2019-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='支出')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='金额')),
                ('members', models.ManyToManyField(to='group_tally.Person', verbose_name='参与人员')),
            ],
        ),
    ]
